## 开发环境配置
## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
##
## redis配置
  redis:
    host: 127.0.0.1
    database: 0
##
##日志配置
logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      baomidou:
        mybatisplus: DEBUG
      cyj:
        spring: DEBUG